---
title: "538_soccer_game_data"
author: "Conor Tompkins"
date: "8/15/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(tidyverse)

theme_set(theme_bw())

data <- read_csv("https://projects.fivethirtyeight.com/soccer-api/club/spi_matches.csv", progress = FALSE)
data
```

```{r}
data %>% 
  rename(home = team1,
         away = team2,
         home_score = score1,
         away_score = score2,
         home_xg = xg1,
         away_xg = xg2,
         home_nsxg = nsxg1,
         away_nsxg = nsxg2) %>% 
  #select(-c(team1, team2)) %>% 
  mutate(teams = str_c(home, away, sep = " .vs ")) %>% 
  select(date, league, teams, home, away, home_score, away_score, home_xg, away_xg, home_nsxg, away_nsxg) %>% 
  #filter(league == "Barclays Premier League") %>% 
  gather(venue, team, -c(date:teams, home_score:away_nsxg)) -> df

df %>% 
  filter(venue == "home") -> home

df %>% 
  filter(venue == "away") -> away

bind_rows(home, away) %>% 
  arrange(date, teams) %>%
  arrange(team, league, date) %>% 
  group_by(team, league) %>% 
  mutate(game_number = dense_rank(date)) %>% 
  ungroup() -> df_games


df_games %>%
  select(date, league, 
         teams, team, 
         game_number, venue, 
         home_score, away_score, 
         home_xg, away_xg, 
         home_nsxg, away_nsxg) %>% 
  mutate(team_score = case_when(venue == "home" ~ home_score,
                                venue == "away" ~ away_score),
         opp_score = case_when(venue == "away" ~ home_score,
                               venue == "home" ~ away_score),
         team_xg = case_when(venue == "home" ~ home_xg,
                             venue == "away" ~ away_xg),
         opp_xg = case_when(venue == "away" ~ home_xg,
                            venue == "home" ~ away_xg),
         team_nsxg = case_when(venue == "home" ~ home_nsxg,
                               venue == "away" ~ away_nsxg),
         opp_nsxg = case_when(venue == "away" ~ home_nsxg,
                              venue == "home" ~ away_nsxg)) %>% 
  select(league, teams, team, 
         date, game_number, venue, 
         home_score, away_score, 
         team_score, opp_score, 
         home_xg, away_xg, 
         team_xg, opp_xg, 
         home_nsxg, away_nsxg, 
         team_nsxg, opp_nsxg) %>% 
  na.omit( )-> df_team
  #colnames()
  #gather(score_measure, score_value, -c(league:away_score, home_xg:opp_nsxg)) %>% 
  #colnames()
  #gather(xg_measure, xg_value, -c(league:away_xg, home_nsxg:score_value)) %>% 
  #colnames()
  #gather(nsxg_measure, nsxg_value, -c(league:away_nsxg, score_measure:xg_value)) %>% 
  #colnames()
  #filter(!is.na(home_score)) -> df_team
```

```{r eval = FALSE}
team_filter <- "Leicester City"
df_team %>% 
  filter(team == team_filter) %>% 
  select(team, game_number, team_score, opp_score) %>% 
  gather(score_measure, score_value, -c(team, game_number)) %>% 
  ggplot(aes(game_number, score_value, color = score_measure)) +
  geom_point() +
  geom_smooth()

df_team %>% 
  filter(team == team_filter) %>% 
  select(team, game_number, team_xg, opp_xg) %>% 
  gather(xg_measure, xg_value, -c(team, game_number)) %>%
  ggplot(aes(game_number, xg_value, color = xg_measure)) +
    geom_point() +
    geom_smooth()

df_team %>% 
  filter(team == team_filter) %>% 
  select(team, game_number, team_nsxg, opp_nsxg) %>% 
  gather(nsxg_measure, nsxg_value, -c(team, game_number)) %>%
  ggplot(aes(game_number, nsxg_value, color = nsxg_measure)) +
    geom_point() +
    geom_smooth()
```


```{r eval = FALSE}
league_filter <- "Barclays Premier League"

df_team %>%
  filter(league == league_filter) %>% 
  mutate(xg_diff = team_xg - opp_xg) %>% 
  group_by(team) %>% 
  summarize(xg_diff = sum(xg_diff)) %>% 
  arrange(desc(xg_diff)) %>% 
  mutate(team = as.factor(team)) %>% 
  select(team) %>% 
  unlist() -> team_fct

#trying to turn this into geom_tile, need to complete() to introduce NAs then comvert to 0s
df_team %>% 
  filter(league == league_filter) %>% 
  select(team, game_number, team_xg, opp_xg) %>% 
  mutate(team_xg = round(team_xg, 1),
         opp_xg = round(opp_xg, 1),
         xg_diff = team_xg - opp_xg) %>% 
  mutate(team = factor(team, levels = team_fct)) %>% 
  group_by(team, team_xg, opp_xg) %>% 
  mutate(n = n()) %>% 
  #count(team, team_xg, opp_xg, xg_diff) %>% 
  ggplot(aes(team_xg, opp_xg, fill = n)) +
    geom_jitter(alpha = .3) +
    #geom_tile() +
    #stat_density_2d(aes(fill = stat(level)), geom = "polygon") +
    facet_wrap(~team) +
  scale_fill_viridis_c("Number of games") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme(panel.grid = element_blank())
```

```{r eval = FALSE}
#animating per game number distance network graphs

library(widyr)
library(tidygraph)
library(ggraph)
library(igraph)


df_team %>% 
  filter(league == "Barclays Premier League") %>% 
  select(team, venue, date, game_number, team_xg, opp_xg) %>% 
  group_by(team) %>% 
  mutate(team_xg_cum = cumsum(team_xg),
         opp_xg_cum = cumsum(opp_xg)) %>% 
  ungroup() -> df_cum

df_cum %>% 
  #group_by(game_number) %>% 
  filter(game_number == 40) %>% 
  pairwise_dist(team, team_xg, opp_xg) %>% 
  mutate(distance = distance^2) -> df_dist
  #ungroup() %>% 
  #group_by(game_number) %>% 
  #nest() -> df_dist

df_dist %>%
  #as_tbl_graph() %>% 
  graph_from_data_frame(directed = FALSE) %>% 
  simplify(remove.multiple = TRUE) %>% 
  ggraph(layout = "drl") +
  geom_edge_fan() +
  geom_node_label(aes(label = name))
  


```