---
title: "538_soccer_distance"
author: "Conor Tompkins"
date: "8/15/2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r}
library(tidyverse)
library(broom)
library(ggraph)
library(tidygraph)
library(viridis)

set_graph_style()

df <- read_csv("https://projects.fivethirtyeight.com/soccer-api/club/spi_global_rankings.csv", progress = FALSE)
df

df %>% 
  select(name, league) -> df_team_league

df %>% 
  select(league, spi) %>% 
  group_by(league) %>% 
  summarize(spi_league = median(spi)) %>% 
  arrange(desc(spi_league)) -> df_league_spi
```

```{r}
df %>% 
  group_by(league) %>% 
  mutate(off_z = scale(off),
         def_z = scale(def)) %>% 
  ungroup() -> df_rel_league
```

```{r}
df_rel_league %>% 
  ggplot(aes(off, def, color = league)) +
  geom_jitter(alpha = .5, show.legend = FALSE)
```


```{r}
df_rel_league %>% 
  ggplot(aes(off_z, def_z, color = league)) +
  geom_jitter(alpha = .5, show.legend = FALSE)
```

```{r}
df_rel_league %>% 
  ggplot(aes(off, off_z, color = league)) +
  geom_jitter(alpha = .5, show.legend = FALSE)
```

```{r}
df_rel_league %>% 
  ggplot(aes(def, def_z, color = league)) +
  geom_jitter(alpha = .5, show.legend = FALSE) +
  scale_x_reverse() +
  scale_y_reverse()
```

```{r}
df_rel_league %>% 
  select(name, off_z, def_z) %>% 
  column_to_rownames(var = "name") -> df_dist

df_dist
rownames(df_dist) %>% 
  head()

df_dist <- dist(df_dist, "euclidean", upper = TRUE)
head(df_dist)

df_dist %>% 
  tidy() %>% 
  arrange(desc(distance)) -> df_dist

df_dist %>% 
  count(item1, sort = TRUE) %>% 
  ggplot(aes(item1, n)) +
  geom_point() +
  coord_flip()
```
```{r}
df_dist %>% 
  left_join(df_team_league, by = c("item1" = "name")) %>% 
  left_join(df_team_league, by = c("item2" = "name")) -> df_dist
```

```{r}
df_dist %>% 
  mutate(distance = distance^2) %>% 
  filter(league.x == "United Soccer League",
         league.y == "United Soccer League") %>% 
  summarize(percentile = quantile(distance, probs = .3)) %>% 
  unlist() -> distance_filter
```
```{r}
league1 <- "United Soccer League"
league2 <- NULL
df_dist %>% 
  mutate(distance = distance^2) %>% 
  #filter(item1 == "Pittsburgh Riverhounds") %>% 
  filter(league.x %in% c(league1, league2),
         league.y %in% c(league1, league2)) %>% 
  filter(distance <= distance_filter) %>% 
  distinct(item1, item2, distance) -> test

```

```{r fig.height=15, fig.width=15}
#leave this one alone
league1 <- "United Soccer League"
league2 <- NULL

df_dist %>% 
  mutate(distance = distance^2) %>% 
  filter(league.x == league1,
         league.y == league1) %>% 
  summarize(percentile = quantile(distance, probs = .3)) %>% 
  unlist() -> distance_filter

df_dist %>% 
  mutate(distance = distance^2) %>% 
  filter(league.x %in% c(league1, league2),
         league.y %in% c(league1, league2)) %>% 
  filter(distance <= distance_filter) %>%
  as_tbl_graph() %>% 
  ggraph(layout = "kk", maxiter = 1000) +
    geom_edge_fan(aes(edge_alpha = distance, edge_width = distance)) + 
    geom_node_label(aes(label = name), size = 4) +
    scale_edge_alpha_continuous("Euclidean distance ^2", range = c(.5, 0)) +
    scale_edge_width_continuous("Euclidean distance ^2", range = c(2, 0)) +
  labs(title = str_c(league1, " football club comparisons (relative to league)"),
       subtitle = "Euclidean distance (offensive rating, defensive rating)^2",
       x = NULL,
       y = NULL,
       caption = "538 data, @conor_tompkins")
```

```{r error = TRUE}
#need to find way to "simplify" graph, remove duplicate edges
league1 <- "United Soccer League"
league2 <- "United Soccer League"
df_dist %>% 
  mutate(distance = distance^2) %>% 
  #filter(item1 == "Pittsburgh Riverhounds") %>% 
  filter(league.x %in% c(league1, league2),
         league.y %in% c(league1, league2)) %>% 
  filter(distance <= 1.56) %>%
  as_tbl_graph() %>% 
  convert(to_simple)

df_dist %>% 
  mutate(distance = distance^2) %>%
  filter(league.x %in% c(league1, league2),
         league.y %in% c(league1, league2)) %>% 
  filter(distance <= 1.56) %>%
  as_tbl_graph() %>%
  morph(to_simple) %>% 
  crystallise()

  ggraph(layout = "kk", maxiter = 1000) +
    geom_edge_fan(aes(edge_alpha = distance, edge_width = distance)) + 
    geom_node_label(aes(label = name), size = 4) +
    scale_edge_alpha_continuous(range = c(.7, 0)) +
    scale_edge_width_continuous(range = c(3, 0)) +
  labs(title = "Football comparisons relative to league",
       subtitle = "Euclidean distance (offensive rating, defensive rating)^2",
       x = NULL,
       y = NULL,
       caption = "538 data, @conor_tompkins")

```

```{r fig.height=15, fig.width=15}
league <- "French Ligue 1"

df_dist %>% 
  mutate(distance = distance^2) %>% 
  filter(league.x == league,
         league.y == league) %>% 
  summarize(percentile = quantile(distance, probs = .8)) %>% 
  unlist() -> distance_filter

league1 <- league
league2 <- league
df_dist %>% 
  mutate(distance = distance^2) %>% 
  filter(league.x %in% c(league1, league2),
         league.y %in% c(league1, league2)) %>% 
  filter(distance <= distance_filter) %>%
  as_tbl_graph() %>% 
  mutate(community = as.factor(group_infomap())) %>% 
  #igraph::simplify(.) %>%
  #as_tbl_graph() %>% 
  #convert(to_simple) %>% 
  ggraph(layout = "kk", maxiter = 1000) +
    geom_edge_fan(aes(edge_alpha = distance, edge_width = distance)) + 
    geom_node_label(aes(label = name, color = community), size = 4) +
    scale_edge_alpha_continuous("Euclidean distance ^2", range = c(.5, 0)) +
    scale_edge_width_continuous("Euclidean distance ^2", range = c(2, 0)) +
    scale_color_discrete("Network community") +
  theme_graph() +
    labs(title = str_c(league, " football club comparisons (relative to league)"),
       subtitle = "Euclidean distance (offensive rating, defensive rating)^2",
       #x = NULL,
       #y = NULL,
       caption = "538 data, @conor_tompkins")
```

```{r}
df_league_spi %>% 
  top_n(20) %>% 
  select(league) %>% 
  unlist() -> top_leagues
  

#league1 <- top_leagues
#league2 <- top_leagues
df_dist %>% 
  mutate(distance = distance^2) %>%
  filter(league.x %in% c(top_leagues),
         league.y %in% c(top_leagues)) %>% 
  filter(distance <= 1.5) %>%
  as_tbl_graph() %>% 
  mutate(community = as.factor(group_infomap())) %>% 
  #igraph::simplify(.) %>%
  #as_tbl_graph() %>% 
  #convert(to_simple) %>% 
  ggraph(layout = "kk", maxiter = 10000) +
    geom_edge_fan(aes(edge_alpha = distance, edge_width = distance)) + 
    #geom_node_label(aes(label = name, color = community), size = 4) +
    geom_node_point(aes(color = community), size = 1) +
    scale_edge_alpha_continuous("Euclidean distance ^2", range = c(.05, 0)) +
    scale_edge_width_continuous("Euclidean distance ^2", range = c(1, .01)) +
    scale_color_discrete("Network community") +
    labs(title = "Football club comparisons (relative to league)",
       subtitle = "Euclidean distance (offensive rating, defensive rating)^2",
       caption = "538 data, @conor_tompkins")
```